project_id = "apqrjkobktjcyrxhqwtm"

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.email-connect]
verify_jwt = false

[functions.email-list]
verify_jwt = false

[functions.email-read]
verify_jwt = false

[functions.email-send]
verify_jwt = false

[functions.fdw-health-check]
verify_jwt = false

[functions.fdw-query]
verify_jwt = false
